const EMAIL_SENDER = "romanrem888@gmail.com";
const ACAO = "*";
const STORE_PERIOD = 30;

const START_TRACKING_REGION = "eu-central-1";
const DYNAMODB_REGION = "eu-central-1";
const GET_TRACKED_REGION = "eu-central-1";
const HANDLE_OBSOLETE_DATA = "eu-central-1";
const GET_STAT_FOR_PERIOD_REGION = "eu-central-1";
const GET_PRODUCT_INFO_REGION = "eu-central-1";
const GET_STAT_FOR_DAY_REGION = "eu-central-1";
const FINISH_TRACKING_REGION = "eu-central-1";
const CONTINUE_TRACKING_REGION = "us-west-1";

exports.EMAIL_SENDER = EMAIL_SENDER;
exports.START_TRACKING_REGION = START_TRACKING_REGION;
exports.GET_TRACKED_REGION = GET_TRACKED_REGION;
exports.CONTINUE_TRACKING_REGION = CONTINUE_TRACKING_REGION;
exports.HANDLE_OBSOLETE_DATA = HANDLE_OBSOLETE_DATA;
exports.GET_STAT_FOR_PERIOD_REGION = GET_STAT_FOR_PERIOD_REGION;
exports.GET_STAT_FOR_DAY_REGION = GET_STAT_FOR_DAY_REGION;
exports.GET_PRODUCT_INFO_REGION = GET_PRODUCT_INFO_REGION;
exports.FINISH_TRACKING_REGION = FINISH_TRACKING_REGION;
exports.DYNAMODB_REGION = DYNAMODB_REGION;
exports.ACAO = ACAO;
exports.STORE_PERIOD = STORE_PERIOD;
